// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Company documents
 */
interface CompanyDocumentData {
  /**
   * Name field in *Company*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Logo field in *Company*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  logo: prismic.KeyTextField;

  /**
   * Name Update field in *Company*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company.name_update
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name_update: prismic.KeyTextField;

  /**
   * Short Name field in *Company*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company.short_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  short_name: prismic.KeyTextField;

  /**
   * Location field in *Company*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: company.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  location: prismic.GeoPointField;

  /**
   * Street field in *Company*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company.street
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  street: prismic.KeyTextField;

  /**
   * ZIP field in *Company*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company.zip
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  zip: prismic.KeyTextField;

  /**
   * City field in *Company*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company.city
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  city: prismic.KeyTextField;

  /**
   * Industry field in *Company*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: company.industry
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  industry: prismic.SelectField<
    | "Agency"
    | "Automotive"
    | "Consumer Goods"
    | "Education"
    | "Energy"
    | "Finance"
    | "Logistics"
    | "Insurance"
    | "Media"
    | "Software"
    | "Telco"
    | "Travel"
  >;

  /**
   * Country field in *Company*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Germany
   * - **API ID Path**: company.country
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  country: prismic.SelectField<
    | "Germany"
    | "UK"
    | "Spain"
    | "Netherlands"
    | "Belgium"
    | "France"
    | "Denmark"
    | "Switzerland"
    | "United States"
    | "Luxemburg",
    "filled"
  >;

  /**
   * Image field in *Company*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: company.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Company document from Prismic
 *
 * - **API ID**: `company`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CompanyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CompanyDocumentData>,
    "company",
    Lang
  >;

/**
 * Content for Degree documents
 */
interface DegreeDocumentData {
  /**
   * Name field in *Degree*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: degree.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Description field in *Degree*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: degree.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Startdate field in *Degree*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: degree.startdate
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  startdate: prismic.DateField;

  /**
   * Enddate field in *Degree*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: degree.enddate
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  enddate: prismic.DateField;

  /**
   * Grade field in *Degree*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: degree.grade
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  grade: prismic.KeyTextField;

  /**
   * School field in *Degree*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: degree.school
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  school: prismic.ContentRelationshipField<"school">;
}

/**
 * Degree document from Prismic
 *
 * - **API ID**: `degree`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DegreeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<DegreeDocumentData>, "degree", Lang>;

type HomeDocumentDataSlicesSlice =
  | ServicesSlice
  | ReferencesSlice
  | CallToActionSlice
  | MainStageSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type PageDocumentDataSlicesSlice =
  | ServicesSlice
  | ReferencesSlice
  | CallToActionSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>
  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Name field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Project Name
   * - **API ID Path**: project.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Excerpt field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Project Excerpt
   * - **API ID Path**: project.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  excerpt: prismic.RichTextField;

  /**
   * Link field in *Project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to project
   * - **API ID Path**: project.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Screenshot field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.screenshot
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  screenshot: prismic.ImageField<never>;

  /**
   * Startdate field in *Project*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: project.startdate
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  startdate: prismic.DateField;

  /**
   * Enddate field in *Project*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: project.enddate
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  enddate: prismic.DateField;

  /**
   * Management field in *Project*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: project.management
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  management: prismic.NumberField;

  /**
   * Design field in *Project*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: project.design
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  design: prismic.NumberField;

  /**
   * Code field in *Project*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: project.code
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  code: prismic.NumberField;

  /**
   * Logo field in *Project*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: project.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  logo: prismic.SelectField<
    | "actimonda"
    | "adidas"
    | "alphaneun"
    | "antena3"
    | "axa"
    | "bmg"
    | "congstar"
    | "coremedia"
    | "deutschebahn"
    | "deutschepost"
    | "deutschetelekom"
    | "dailytelegraph"
  >;

  /**
   * Company field in *Project*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project.company
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  company: prismic.ContentRelationshipField<"company">;

  /**
   * Employer field in *Project*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project.employer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  employer: prismic.ContentRelationshipField<"company">;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

/**
 * Content for School documents
 */
interface SchoolDocumentData {
  /**
   * Name field in *School*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: school.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Logo field in *School*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: school.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Short Name field in *School*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: school.short_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  short_name: prismic.KeyTextField;

  /**
   * School Description field in *School*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: school.school_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  school_description: prismic.RichTextField;

  /**
   * Location field in *School*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: school.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  location: prismic.GeoPointField;

  /**
   * Image field in *School*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: school.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Street field in *School*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: school.street
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  street: prismic.KeyTextField;

  /**
   * City field in *School*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: school.city
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  city: prismic.KeyTextField;

  /**
   * ZIP field in *School*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: school.zip
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  zip: prismic.KeyTextField;

  /**
   * Country field in *School*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: school.country
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  country: prismic.SelectField<
    "Germany" | "Spain" | "England" | "United States"
  >;
}

/**
 * School document from Prismic
 *
 * - **API ID**: `school`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SchoolDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SchoolDocumentData>, "school", Lang>;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Settings → Footer Links*
 */
export interface SettingsDocumentDataFooterLinksItem {
  /**
   * Link field in *Settings → Footer Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *Settings → Footer Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;

  /**
   * Footer Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_links: prismic.GroupField<
    Simplify<SettingsDocumentDataFooterLinksItem>
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

/**
 * Content for Skill documents
 */
interface SkillDocumentData {
  /**
   * Name field in *Skill*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skill.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Category field in *Skill*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: skill.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  category: prismic.SelectField<
    | "Methodology"
    | "Business"
    | "Consulting"
    | "Marketing"
    | "Creative"
    | "Code"
    | "Office"
    | "CRM, CMS & Co."
    | "Language"
    | "Project Management"
  >;

  /**
   * Experience field in *Skill*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: skill.experience
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  experience: prismic.NumberField;

  /**
   * Level field in *Skill*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: skill.level
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  level: prismic.NumberField;
}

/**
 * Skill document from Prismic
 *
 * - **API ID**: `skill`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SkillDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SkillDocumentData>, "skill", Lang>;

/**
 * Item in *Social → Social Plattforms*
 */
export interface SocialDocumentDataSocialPlattformsItem {
  /**
   * Label field in *Social → Social Plattforms*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social.social_plattforms[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Social → Social Plattforms*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: social.social_plattforms[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * SVG Icon Path field in *Social → Social Plattforms*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social.social_plattforms[].svg_icon_path
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  svg_icon_path: prismic.KeyTextField;
}

/**
 * Content for Social documents
 */
interface SocialDocumentData {
  /**
   * Social Plattforms field in *Social*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: social.social_plattforms[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_plattforms: prismic.GroupField<
    Simplify<SocialDocumentDataSocialPlattformsItem>
  >;
}

/**
 * Social document from Prismic
 *
 * - **API ID**: `social`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SocialDocumentData>,
    "social",
    Lang
  >;

/**
 * Content for Testimonial documents
 */
interface TestimonialDocumentData {
  /**
   * Name field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Avatar field in *Testimonial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.avatar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  avatar: prismic.ImageField<never>;

  /**
   * Text field in *Testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Date field in *Testimonial*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Employer field in *Testimonial*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.employer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  employer: prismic.ContentRelationshipField<"company">;
}

/**
 * Testimonial document from Prismic
 *
 * - **API ID**: `testimonial`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TestimonialDocumentData>,
    "testimonial",
    Lang
  >;

export type AllDocumentTypes =
  | CompanyDocument
  | DegreeDocument
  | HomeDocument
  | PageDocument
  | ProjectDocument
  | SchoolDocument
  | SettingsDocument
  | SkillDocument
  | SocialDocument
  | TestimonialDocument;

/**
 * Primary content in *CallToAction → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Heading field in *CallToAction → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Subline field in *CallToAction → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.subline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subline: prismic.RichTextField;

  /**
   * Link field in *CallToAction → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link Text field in *CallToAction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Primary content in *MainStage → Primary*
 */
export interface MainStageSliceDefaultPrimary {
  /**
   * Headline field in *MainStage → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: main_stage.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.TitleField;
}

/**
 * Default variation for MainStage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainStageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MainStageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MainStage*
 */
type MainStageSliceVariation = MainStageSliceDefault;

/**
 * MainStage Shared Slice
 *
 * - **API ID**: `main_stage`
 * - **Description**: MainStage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainStageSlice = prismic.SharedSlice<
  "main_stage",
  MainStageSliceVariation
>;

/**
 * Primary content in *References → Primary*
 */
export interface ReferencesSliceDefaultPrimary {
  /**
   * Headline field in *References → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: references.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Excerpt field in *References → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: references.primary.excerpt
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  excerpt: prismic.RichTextField;

  /**
   * Background field in *References → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: references.primary.background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background: prismic.ImageField<never>;
}

/**
 * Primary content in *References → Items*
 */
export interface ReferencesSliceDefaultItem {
  /**
   * Project field in *References → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: references.items[].project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"project">;
}

/**
 * Default variation for References Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReferencesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReferencesSliceDefaultPrimary>,
  Simplify<ReferencesSliceDefaultItem>
>;

/**
 * Slice variation for *References*
 */
type ReferencesSliceVariation = ReferencesSliceDefault;

/**
 * References Shared Slice
 *
 * - **API ID**: `references`
 * - **Description**: References
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReferencesSlice = prismic.SharedSlice<
  "references",
  ReferencesSliceVariation
>;

/**
 * Primary content in *Services → Primary*
 */
export interface ServicesSliceDefaultPrimary {
  /**
   * Headline field in *Services → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Headline
   * - **API ID Path**: services.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.TitleField;
}

/**
 * Primary content in *Services → Items*
 */
export interface ServicesSliceDefaultItem {
  /**
   * Icon field in *Services → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: target
   * - **API ID Path**: services.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<"target" | "edit" | "code", "filled">;

  /**
   * Title field in *Services → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Service Title
   * - **API ID Path**: services.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Services → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Link field in *Services → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://philippboue.de
   * - **API ID Path**: services.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link Text field in *Services → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Link Text
   * - **API ID Path**: services.items[].link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSliceDefaultPrimary>,
  Simplify<ServicesSliceDefaultItem>
>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSlice = prismic.SharedSlice<
  "services",
  ServicesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CompanyDocument,
      CompanyDocumentData,
      DegreeDocument,
      DegreeDocumentData,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProjectDocument,
      ProjectDocumentData,
      SchoolDocument,
      SchoolDocumentData,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      SettingsDocumentDataFooterLinksItem,
      SkillDocument,
      SkillDocumentData,
      SocialDocument,
      SocialDocumentData,
      SocialDocumentDataSocialPlattformsItem,
      TestimonialDocument,
      TestimonialDocumentData,
      AllDocumentTypes,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      MainStageSlice,
      MainStageSliceDefaultPrimary,
      MainStageSliceVariation,
      MainStageSliceDefault,
      ReferencesSlice,
      ReferencesSliceDefaultPrimary,
      ReferencesSliceDefaultItem,
      ReferencesSliceVariation,
      ReferencesSliceDefault,
      ServicesSlice,
      ServicesSliceDefaultPrimary,
      ServicesSliceDefaultItem,
      ServicesSliceVariation,
      ServicesSliceDefault,
    };
  }
}
