import "./globals.css";
import type { Metadata } from "next";
import clsx from "clsx";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
	subsets: ["latin"],
	variable: "--font-montserrat",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={clsx(montserrat.variable)}>
			<body>{children}</body>
		</html>
	);
}
