// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  contact_form: dynamic(() => import("./ContactForm")),
  key_value_table: dynamic(() => import("./KeyValueTable")),
  main_stage: dynamic(() => import("./MainStage")),
  map: dynamic(() => import("./Map")),
  projects_table: dynamic(() => import("./ProjectsTable")),
  references: dynamic(() => import("./References")),
  services: dynamic(() => import("./Services")),
  skills_table: dynamic(() => import("./SkillsTable")),
  tables: dynamic(() => import("./Tables")),
  textblock: dynamic(() => import("./Textblock")),
};
