// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  references: dynamic(() => import("./References")),
  services: dynamic(() => import("./Services")),
};
